spring.data.mongodb.uri=mongodb+srv://rmamedova2010_db_user:JxCskKoHnwdPScjG@chatcluster.tegho2y.mongodb.net/?appName=ChatCluster

# logs queries 
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG