spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=chat_db

# Ensure the app listens to the port Hugging Face assigns
server.port=${PORT:7860}

firebase.apiKey=${FIREBASE_API_KEY}
firebase.authDomain=${FIREBASE_AUTH_DOMAIN}
firebase.projectId=${FIREBASE_PROJECT_ID}
firebase.storageBucket=${FIREBASE_STORAGE_BUCKET}
firebase.messagingSenderId=${FIREBASE_MESSAGING_SENDER_ID}
firebase.appId=${FIREBASE_APP_ID}